In [2]:
# Random forest using cross validation scheme

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, KFold, train_test_split
# Load the Iris dataset
iris = load_iris()
X, y = iris.data, iris.target
# Create a Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
# Define the number of folds for cross-validation
num_folds = 3
kf = KFold(n_splits=num_folds, shuffle=True, random_state=42)
# Perform cross-validation
cross_val_scores = cross_val_score(rf_classifier, X, y, cv=kf)
# Display the cross-validation scores
print("Cross-Validation Scores: ",cross_val_scores)
print("Mean Accuracy: {:.2f}%".format(np.mean(cross_val_scores)*100))


Cross-Validation Scores:  [0.98 0.92 0.96]
Mean Accuracy: 95.33%


In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
rf_classifier.fit(X_train, y_train)
y_pred = rf_classifier.predict(X_test)
print(accuracy_score(y_test,y_pred))


1.0


In [4]:
print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [5]:
print(confusion_matrix(y_test,y_pred))


[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
